service:
  name: user-friendly-api-client
  host: localhost
  port: 8000
api:
  protocol: 'http'
  host: localhost
  port: 3000
  access_token:
    1001: 'Bearer synZWYC6mGpWQXqLYGeAbncBh4CCwxu2'
    11: 'Bearer Dh12WipmTDZCXrk5wTuSRPzCYUoUcmXY'
template_engine:
  is_cached: true
